//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public int AuthenticUserId { get; set; }
        public string ProductName { get; set; }
        public string ProductImg { get; set; }
        public Nullable<System.DateTime> ProductCreationDate { get; set; }
        public int ProductPass { get; set; }
        public string category { get; set; }
    
        public virtual AuthenticUser AuthenticUser { get; set; }
    }
}
